# Generated by Django 4.1.2 on 2022-10-14 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('dob', models.DateField(null=True, verbose_name='Date of birth')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.IntegerField()),
                ('balance', models.FloatField()),
                ('password', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=20)),
                ('product_desc', models.CharField(max_length=100)),
                ('product_img', models.ImageField(upload_to='images/')),
                ('prod_sell_price', models.IntegerField()),
                ('prod_cost_price', models.IntegerField()),
                ('stock_unit', models.IntegerField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='User_Role',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('role_name', models.CharField(max_length=20)),
                ('role_desc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User_Purchase',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('purchase_date', models.DateField()),
                ('total_unit', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.product')),
                ('purchased_by_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchased_by_user', to='account.myuser')),
                ('purchased_from_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchased_from_user', to='account.myuser')),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.user_role'),
        ),
    ]
