# Generated by Django 4.1.2 on 2022-10-17 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_product_created_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.myuser'),
        ),
    ]
