# Generated by Django 4.1.2 on 2022-10-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_product_created_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_purchase',
            name='purchase_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
