# Generated by Django 4.1.2 on 2022-10-18 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_product_created_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.myuser'),
        ),
    ]
