# Generated by Django 4.1.2 on 2022-10-18 13:14

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_myuser_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='balance',
            field=models.FloatField(validators=[account.models.CustomMinvalue(1)]),
        ),
        migrations.AlterField(
            model_name='user_purchase',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.product'),
        ),
    ]
