# Generated by Django 4.1.2 on 2022-10-19 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_product_created_by_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_unit',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
